function plot
%initialize theater (canvas on which objects are plotted)
%size=10
tp = theaterPlot();%'XLimit',[-size size],...
    %'YLimit',[-size size],'ZLimit',[-size size]);
    
%plot body frames    
op = orientationPlotter(tp,'DisplayName','Data',...
    'LocalAxesLength',2,'MarkerSize',2,...
    'FontSize',10);
orientations=cat(3,zeros(3,3),config_1(1:3,1:3),...
    config_2(1:3,1:3),config_3(1:3,1:3),...
    config_4(1:3,1:3));
positions=[zeros(1,3);transpose(config_1(1:3,4));...
    transpose(config_2(1:3,4));...
    transpose(config_3(1:3,4));...
    transpose(config_4(1:3,4))];
labels={'0,0,0';'\theta/4';'\theta/2';'3\theta/4';'\theta'};
plotOrientation(op,orientations,positions,labels);

%plot screw axis
trajPlotter=trajectoryPlotter(tp,...
    'DisplayName','Screw Axis', 'Linewidth', 1,...
    'color', 'm');
plotTrajectory(trajPlotter,axis_points_cell_array);

end