function Robo_plot(mode,varargin)
switch mode
    case init %input:display name,
        figure()
        %initialize theater (canvas on which objects are plotted)
        %size=10
        tp = theaterPlot();%'XLimit',[-size size],...
        %'YLimit',[-size size],'ZLimit',[-size size]);
        op = orientationPlotter(tp,'DisplayName',varargin{1},...
        'LocalAxesLength',2,'MarkerSize',2,...
        'FontSize',10);
        trajPlotter=trajectoryPlotter(tp,...
        'DisplayName','Screw Axis', 'Linewidth', 1,...
        'color', 'm');
    case frame %input:orientations,positions,labels
        %plot body frames
        orientations=varargin{1};
        %orientations=cat(3,zeros(3,3),config_1(1:3,1:3),...
            %config_2(1:3,1:3),config_3(1:3,1:3),...
            %config_4(1:3,1:3));
        positions=varargin{2};
        %positions=[zeros(1,3);transpose(config_1(1:3,4));...
            %transpose(config_2(1:3,4));...
            %transpose(config_3(1:3,4));...
            %transpose(config_4(1:3,4))];
        labels=varargin{3};
        %labels={'0,0,0';'\theta/4';'\theta/2';...
            %'3\theta/4';'\theta'};
        plotOrientation(op,orientations,positions,labels);
    case points %input:points_cell_array
        plotTrajectory(trajPlotter,points_cell_array);
    otherwise
        error('invalid input for "mode"')
end
end